### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by lmartins** [klorenz/atom-open-plus#8]
Edit: Forgot to actually describe the steps.
Essentially happens whenever I try to use the open file feature, so Im not sure this is related to the plugin or my Atom install. Would appreciate your input.

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.4
**Thrown From**: [open-plus](https://github.com/klorenz/atom-open-plus) package, v0.3.2
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/luismartins/.atom/packages/open-plus/lib/open-plus.coffee:92

TypeError: undefined is not a function
  at Object.module.exports.openPlus (/Users/luismartins/.atom/packages/open-plus/lib/open-plus.coffee:92:29)
  at atom-workspace.<anonymous> (/Users/luismartins/.atom/packages/open-plus/lib/open-plus.coffee:25:63)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:22.6.0 core:close (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:20.5.0 fuzzy-finder:toggle-file-finder (div.settings-view.pane-item)
     -0:19.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 13x -0:17.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:14.1.0 vim-mode:move-to-next-whole-word (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:13.6.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:12.7.0 vim-mode:find (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:10 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:10 blur (atom-text-editor.editor.mini.is-focused)
     -0:07.0 vim-mode:find (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:07.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:04.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:04.3.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:02.5.0 open-plus:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:00.3.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ],
    "disabledPackages": [
      "symbols-view",
      "linter-jscs",
      "autocomplete",
      "autohide-tree-view",
      "powerline",
      "language-objective-c",
      "archive-view",
      "language-clojure",
      "language-c",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "welcome",
      "git-difftool",
      "layout-manager"
    ],
    "projectHome": "/Users/luismartins/Sites",
    "ignoredNames": [
      ".DS_Store",
      "bower_components",
      "node_modules",
      "build",
      "jspm_packages"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
atom-beautify, v0.28.0
atom-ctags, v4.1.2
chester-atom-syntax, v0.1.1
color-picker, v2.0.4
css-snippets, v0.8.0
docblockr, v0.7.2
emmet, v2.3.10
expand-region, v0.1.0
javascript-snippets, v1.0.0
language-less, v0.27.0
linter, v0.12.7
linter-jshint, v0.1.6
linter-php, v0.0.15
minimap, v4.9.4
minimap-bookmarks, v0.1.0
open-plus, v0.3.2
php-twig, v4.0.0
selection-outlines, v0.2.0
symbols-tree-view, v0.9.3
vim-mode, v0.51.0
vim-surround, v0.6.1
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by mykz** [comment]
The error has todo with the **Deprecated APIs**. A working version can be found here:
`https://github.com/mykz/atom-open-plus`

**Comment by pascalpp** [comment]
I installed this^ by cloning it, and replacing the contents of the existing package with the content of the cloned repo, and then running npm install in there. Is there a better/prescribed way of doing that?

**Comment by mykz** [comment]
@pascalpp until @klorenz merges my pull request and publishes a new version to Atom the only way is the way you have described.

**Comment by pascalpp** [comment]
:+1:

**Comment by ErebusBat** [comment]
:+1: 

Using @mykz repo worked for me (clone,`npm install`)

**Comment by klorenz** [comment]
fixed

**Comment by pascalpp** [comment]
@klorenz I've uninstalled open-plus and reinstalled version 0.5.1, but this is still happening for me. Here's the stack trace, fwiw:

```
TypeError: undefined is not a function
  at Object.module.exports.openPlus (/Users/pascal/.atom/packages/open-plus/lib/open-plus.coffee:112:21)
  at atom-workspace.<anonymous> (/Users/pascal/.atom/packages/open-plus/lib/open-plus.coffee:27:63)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)
```

**Comment by pascalpp** [comment]
@klorenz Not sure why, but this bit seems to be the culprit:

```
# {Range} = require 'atom'

{Range} = atom
```

if I uncomment that first line and remove the second line, it works fine.

**Comment by pascalpp** [comment]
A bit more digging: apparently the object you get back from require('atom') is not the same as the `atom` global:

![image](https://cloud.githubusercontent.com/assets/1355312/8407373/f2a059e4-1e33-11e5-9e04-f886aea18d83.png)

**Comment by pascalpp** [comment]
and more:

![image](https://cloud.githubusercontent.com/assets/1355312/8407389/20cd5010-1e34-11e5-9ef2-6a2d60e45a8e.png)
